<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get msg</name>
  <uuid>9ec7050f-1ebc-4c20-a721-cf1b6909ff40</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the msg of 'Eligibility for the Service' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
