<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Calc_Price_area</name>
  <uuid>451effc3-3e55-45dd-9c67-f9f3d5d3014b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
	set decision to a new CostOuput where
		the ServiceName is "Issue Baladi" , 
		the Type is 1 , 
		the year1 is a new CostPerYear where 
	Ma3fe is false , 
	the Cost is   'Issue Price per meter' * the Area , 
		the year2 is  a new CostPerYear where 
	Ma3fe is false , 
	the Cost is   0,  
		the year3 is  a new CostPerYear where 
	Ma3fe is false , 
	the Cost is   0   , 
		the year4 is  a new CostPerYear where 
	Ma3fe is false , 
	the Cost is  0  , 
		the year5 is  a new CostPerYear where 
	Ma3fe is false , 
	the Cost is   0  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
